# Generated by Django 5.1.4 on 2025-01-16 00:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fabricante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('pais', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='producto',
            name='f_vencimiento',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='fabricante',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='productos.fabricante'),
        ),
    ]
