# Generated by Django 4.2.18 on 2025-01-18 01:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('correo', models.CharField(max_length=70, unique=True)),
                ('telefono', models.CharField(max_length=15)),
                ('tipo_licencia', models.CharField(choices=[('A', 'Clase A'), ('B', 'Clase B'), ('C', 'Clase C')], max_length=1)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Clase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('tipo', models.CharField(choices=[('T', 'Clase Teorica'), ('P', 'Clase Practica')], max_length=1)),
                ('descripcion', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelo', models.CharField(max_length=50)),
                ('patente', models.CharField(max_length=10)),
                ('transmision', models.CharField(choices=[('M', 'Manual'), ('A', 'Automática')], default='M', max_length=1)),
                ('estado', models.CharField(choices=[('D', 'Disponible'), ('M', 'En Mantención')], default='D', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Instructor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('correo', models.CharField(max_length=70)),
                ('telefono', models.CharField(max_length=15)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DetalleClase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(null=True)),
                ('hora', models.TimeField(max_length=5, null=True)),
                ('estado', models.CharField(blank=True, choices=[('P', 'Pendiente'), ('E', 'En curso'), ('A', 'Aprobada'), ('R', 'Reprobada')], max_length=1)),
                ('alumno', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='clases.alumno')),
                ('clase', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='clases.clase')),
                ('instructor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='clases.instructor')),
                ('vehiculo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='clases.vehiculo')),
            ],
        ),
    ]
