# Generated by Django 4.2.18 on 2025-01-18 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clases', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalleclase',
            name='resultado',
            field=models.CharField(blank=True, max_length=2000),
        ),
        migrations.AlterField(
            model_name='alumno',
            name='correo',
            field=models.CharField(max_length=70),
        ),
        migrations.AlterField(
            model_name='detalleclase',
            name='estado',
            field=models.CharField(choices=[('P', 'Pendiente'), ('E', 'En curso'), ('A', 'Aprobada'), ('R', 'Reprobada')], default='P', max_length=1),
        ),
    ]
