# Generated by Django 5.1.3 on 2024-11-27 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartphone', '0007_remove_smartphone_maker_delete_maker'),
    ]

    operations = [
        migrations.AddField(
            model_name='smartphone',
            name='status',
            field=models.CharField(choices=[('disponible', 'Disponible'), ('agotado', 'Agotado')], default='disponible', max_length=20),
        ),
    ]
