'Una empresa dedicada a la venta de automóviles ofrece distintos modelos. Producto de ello, se 
'necesita almacenar la patente, marca, modelo, color y el precio de venta de cada uno. Y para sus 
'clientes, el nombre, correo electrónico, dirección, RUT y celular. Los clientes pueden ser dados 
'de alta o baja. Y también se requiere registrar las ventas de un cliente, y llevar una historia de las 
'mantenciones  realizadas,  para  poder  avisarle  de  forma  anticipada  las  que  se  realizan  cada 
'número de Kms o cada mes, dependiendo del vehículo.

@startuml Drilling

entity "Automóviles"{
    idAutomovil
    --
    patente
    marca
    modelo
    color
    precioVenta
}
entity "Clientes"{}
entity "Ventas"{}
entity "Mantenciones"{}

@enduml