# Generated by Django 5.1.4 on 2025-01-16 23:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0003_producto_fabricante'),
    ]

    operations = [
        migrations.AddField(
            model_name='fabricante',
            name='pais',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='producto',
            name='f_vencimiento',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='fabricante',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='productos.fabricante'),
        ),
    ]
