# Generated by Django 5.1.4 on 2025-01-08 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_detail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('received', 'Recibido'), ('doing', 'Reparación'), ('tests', 'Pruebas'), ('ready', 'Listo'), ('delivered', 'Entregado')], default='received', max_length=15),
        ),
    ]
