# Generated by Django 4.2.17 on 2025-01-10 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='user',
        ),
        migrations.AddField(
            model_name='cliente',
            name='correo',
            field=models.CharField(default='', max_length=70),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cliente',
            name='nombre',
            field=models.CharField(default='user', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pista',
            name='tipo',
            field=models.CharField(choices=[('niños', 'Niños'), ('jovenes', 'Jovenes'), ('adultos', 'Adultos')], max_length=50),
        ),
    ]
