# Generated by Django 4.2.17 on 2025-01-10 22:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0002_remove_cliente_user_cliente_correo_cliente_nombre_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reserva',
            name='cliente',
        ),
        migrations.AlterField(
            model_name='reserva',
            name='pista',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='management.pista'),
        ),
    ]
