# Generated by Django 5.1.3 on 2024-11-26 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartphone', '0002_smartphone_ram_smartphone_screen_size_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='smartphone',
            name='height',
            field=models.CharField(choices=[('S', 'Small'), ('M', 'Medium'), ('B', 'Big')], default='S', max_length=1),
        ),
    ]
