# Generated by Django 5.1.4 on 2024-12-05 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='avatar',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='person',
            name='birthday',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='curriculum',
            field=models.FileField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='person',
            name='dinner_time',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='facebook_page',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='is_active',
            field=models.BooleanField(default=True, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='monthly_salary',
            field=models.FloatField(default=0.0, null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='tag',
            field=models.SlugField(null=True),
        ),
        migrations.AddField(
            model_name='person',
            name='yearly_salary',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='age',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='creation_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
    ]
